-- ============================================================
--  Dark Cinema / Quest Schema & Initial Seed Data for Supabase
-- ============================================================

-- 1. Tables
CREATE TABLE IF NOT EXISTS rooms (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(100) NOT NULL UNIQUE,
    description TEXT,
    capacity    INT          NOT NULL,
    min_people  INT          NOT NULL,
    theme_code  VARCHAR(50),
    type        VARCHAR(20)  NOT NULL DEFAULT 'CINEMA',
    active      BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS time_slots (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    room_id    BIGINT      NOT NULL REFERENCES rooms(id) ON DELETE CASCADE,
    start_time TIME        NOT NULL,
    end_time   TIME        NOT NULL,
    active     BOOLEAN     NOT NULL DEFAULT TRUE,
    UNIQUE (room_id, start_time)
);

CREATE TABLE IF NOT EXISTS slot_reservations (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    room_id          BIGINT      NOT NULL REFERENCES rooms(id) ON DELETE CASCADE,
    time_slot_id     BIGINT      NOT NULL REFERENCES time_slots(id) ON DELETE CASCADE,
    reservation_date DATE        NOT NULL,
    created_at       TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (time_slot_id, reservation_date)
);

CREATE TABLE IF NOT EXISTS reviews (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR(100),
    stars      INT         NOT NULL CHECK (stars BETWEEN 1 AND 5),
    body       TEXT        NOT NULL,
    venue      VARCHAR(20) NOT NULL DEFAULT 'CINEMA',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS admins (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username   VARCHAR(50)  NOT NULL UNIQUE,
    password   VARCHAR(255) NOT NULL,
    is_root    BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS settings (
    key   VARCHAR(100) PRIMARY KEY,
    value TEXT NOT NULL
);

-- Indexes
CREATE INDEX IF NOT EXISTS idx_slot_res_date  ON slot_reservations(reservation_date);
CREATE INDEX IF NOT EXISTS idx_slot_res_slot  ON slot_reservations(time_slot_id);
CREATE INDEX IF NOT EXISTS idx_reviews_date   ON reviews(created_at);
CREATE INDEX IF NOT EXISTS idx_reviews_venue  ON reviews(venue);

-- Enable RLS on all tables
ALTER TABLE rooms ENABLE ROW LEVEL SECURITY;
ALTER TABLE time_slots ENABLE ROW LEVEL SECURITY;
ALTER TABLE slot_reservations ENABLE ROW LEVEL SECURITY;
ALTER TABLE reviews ENABLE ROW LEVEL SECURITY;
ALTER TABLE admins ENABLE ROW LEVEL SECURITY;
ALTER TABLE settings ENABLE ROW LEVEL SECURITY;

-- Public RLS Policies (Allow reads for public UI, service_role bypasses RLS for admin writes)
CREATE POLICY "Public rooms read" ON rooms FOR SELECT USING (true);
CREATE POLICY "Public slots read" ON time_slots FOR SELECT USING (true);
CREATE POLICY "Public reservations read" ON slot_reservations FOR SELECT USING (true);
CREATE POLICY "Public settings read" ON settings FOR SELECT USING (true);
CREATE POLICY "Public reviews read" ON reviews FOR SELECT USING (true);
CREATE POLICY "Public review insert" ON reviews FOR INSERT WITH CHECK (true);

-- Seed Data
INSERT INTO rooms (id, name, description, capacity, min_people, theme_code, active, type)
VALUES
    (1, 'Сгоревший дом',
     'Интерактивный хоррор-опыт с живыми актёрами. Погрузитесь в атмосферу ужаса.',
     8, 2, 'LIVING', TRUE, 'CINEMA'),
    (2, 'Комната Мама',
     'Хоррор на борту поезда. Путешествие, из которого нет возврата.',
     14, 4, 'PASSENGER', TRUE, 'CINEMA'),
    (3, 'Dark Quest',
     'Хоррор-квест в реальности. Тёмные комнаты, живые актёры, настоящий ужас.',
     15, 4, 'DEAD', TRUE, 'QUEST')
ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description,
    capacity = EXCLUDED.capacity, min_people = EXCLUDED.min_people,
    theme_code = EXCLUDED.theme_code, active = EXCLUDED.active, type = EXCLUDED.type;

-- Time slots for Room 1
INSERT INTO time_slots (room_id, start_time, end_time) VALUES
    (1,'13:00','15:00'),(1,'15:00','17:00'),(1,'17:00','19:00'),(1,'19:00','21:00'),
    (1,'21:00','23:00'),(1,'23:00','01:00'),(1,'01:00','03:00'),(1,'03:00','05:00')
ON CONFLICT DO NOTHING;

-- Time slots for Room 2
INSERT INTO time_slots (room_id, start_time, end_time) VALUES
    (2,'13:00','15:00'),(2,'15:00','17:00'),(2,'17:00','19:00'),(2,'19:00','21:00'),
    (2,'21:00','23:00'),(2,'23:00','01:00'),(2,'01:00','03:00'),(2,'03:00','05:00')
ON CONFLICT DO NOTHING;

-- Time slots for Room 3 (Quest)
INSERT INTO time_slots (room_id, start_time, end_time) VALUES
    (3,'11:00','12:20'),(3,'12:20','13:40'),(3,'13:40','15:00'),
    (3,'15:00','16:20'),(3,'16:20','17:40'),(3,'17:40','19:00'),
    (3,'19:00','20:20'),(3,'20:20','21:40'),(3,'21:40','23:00'),
    (3,'23:00','00:20'),(3,'00:20','01:40'),(3,'01:40','03:00')
ON CONFLICT DO NOTHING;

-- Settings
INSERT INTO settings (key, value) VALUES
    ('whatsapp_number',       '77005767848'),
    ('youtube_url',           'https://youtu.be/OpThntO9ixc?si=LcP6FJ0wI3iDmYYL'),
    ('youtube_url_3',         'https://youtube.com/shorts/PHZwtpGp2qM?si=fucOShtu7ztVU698'),
    ('quest_whatsapp_number', '77005767848'),
    ('quest_youtube_url',     ''),
    ('quest_hero_bg',         '')
ON CONFLICT DO NOTHING;
